### PR TITLE
Add condition immuity to monster page

### LINKED ISSUE #471: Bug: Monster pages missing condition immunities
(Thanks to PhazeLink on Discord for flagging this one)

The condition immunities of monsters are returned by the API, but are not being displayed on the website. It would be could if we could add these to the `/monsters/[id].vue` page, probably after the *Damage Immunities*.

### Reproduction

1) Visit the page of a monster with condition immunities on the Open5e live site. The [Bar Brawl](https://open5e.com/monsters/bar-brawl) was flagged in the original Discord post. Notice that there are no condition immunities in the statblock.

2) Compare this with the [Open5e API page for the Bar Brawl](https://api.open5e.com/monsters/bar-brawl/), which returns conditions immunities

Screenshot 2024-03-01 at 22 06 49

Screenshot 2024-03-01 at 21 53 39

### PR DESCRIPTION
**Pull request by Jayanth-Parthsarathy**
Resolves #471.
Added condition immunities that was missing from the monster page.

image

### CODE REVIEW

**Review by calumbell — CHANGES_REQUESTED** [review]
Thanks for getting this sorted so quickly, I didn't even have time to assign the issue!

Before merging this to `staging` would you be able to fix the formatting on the `<span>` tag? The closing tags are looking a little strange. People have been having issues with the formatter doing wonky things like this all over the codebase! (Fixed in PR #461, but this hasn't been merged to staging yet)

Thanks again for contributing!

**Comment by Jayanth-Parthsarathy** [comment]
> Thanks for getting this sorted so quickly, I didn't even have time to assign the issue!
> 
> Before merging this to `staging` would you be able to fix the formatting on the `<span>` tag? The closing tags are looking a little strange. Something like this would be preferred:
> 
> ```
> <span class="font-bold after:content-['_']">
>   Condition Immunities
> </span>
> ```
> 
> But otherwise, this is exactly what we were looking for! People have reported having issues with the formatter doing wonky things like this all over the codebase (Fixed in PR #461, but this hasn't been merged to staging yet)
> 
> Thanks again for contributing!

Sure No problem. It was my mistake for not noticing the weird formatting before submitting a PR :( I have changed the formatting in my second commit.

**Review by calumbell — APPROVED** [review]
Thanks for fixing that! Loks great, and runs without an errors on local.

I'll go ahead and get this merged to staging. Thanks again for your contribution!

**Comment by calumbell** [comment]
It looks like the PR validation is suck (this happens somethings). I am going to close and re-open the PR to see if that fixes it.

**Pull request merged**
