### PR TITLE
Bugfix: Prettier & ESLint updates / fixing new linting errors

### LINKED ISSUE #410: Adjust Prettier config to resolve style issues
Currently, prettier is enforcing some styles that are hard to read and confusing.

Key examples identified in #404 by @calumbell:

- [Self closing tags](https://github.com/open5e/open5e/pull/404#discussion_r1237082442) for components that don't contain slot contents
- [Enforce strings and tags on separate lines](https://github.com/open5e/open5e/pull/404#discussion_r1237151991)
- [Classes in templates should be displayed one-per line](https://github.com/open5e/open5e/pull/404#discussion_r1237292268) when beyond a reasonable length, for readability. Especially crucial when using tailwind.
- [Angle brackets are all funky](https://github.com/open5e/open5e/pull/404#discussion_r1237304724) and this is being enforced by pretter/eslint

Please add additional ideas to comments if you spot something that could use a change.

### PR DESCRIPTION
**Pull request by calumbell**
This PR closes #410 by adjusting the Prettier and ESLint configs so that;

1) The linter catches a lot more dodgy formatting.
2) Prettier & ESLint are not fighting (ie. ESLint highlights an error due to Prettier's formatting)

The bulk of the work in this PR involved fixing the numerous new linter errors introduced by the changes. This is why there are so many small changes across many files.

The only point in the original issue which has not been addressed is how to style overlong strings of Tailwind classes. From my research, there doesn't appear to be a clear consensus on how to manage this. And as any solution would be highly opinionated, it probably ought to be discussed first

### CODE REVIEW

**Comment by Sturlen** [comment]
> The only point in the original issue which has not been addressed is how to style overlong strings of Tailwind classes. From my research, there doesn't appear to be a clear consensus on how to manage this. And as any solution would be highly opinionated, it probably ought to be discussed first

I don't think it's worth holding up the linting changes for this, since it's a separate issue. The current changes all look good regardless!

**Comment by calumbell** [comment]
Looks like is now passing the PR validation thanks to the bug fixes made in PRs #462 and #463

**Comment by calumbell** [comment]
Merging conflict have been resolved, but now the tests need to be re-run. A quick close and reopen should do the trick.

**Comment by calumbell** [comment]
Resolved some more merge conflicts and tests are stuck again. Time to close and reopen the PR one more time

**Review by eepMoody — APPROVED** [review]

**Pull request merged**
