### PR TITLE
[FIX][OPEN5E][ISSUE-450] Fix for blank page on compact monster stat blocks

### PR DESCRIPTION
**Pull request by drewdoesdev**
Resolves [issue 450: Some compact stat blocks crashing](https://github.com/open5e/open5e/issues/450);

## Description
- Upon investigation, the issue seemed to be that the template for compact stat blocks was calling the length property of reactions and legendary actions, which return null from the data when undefined.  To resolve this issue, optional chaining was added to these property to prevent crashing.

### Production Site
**Gnoll**
image

**Aboleth**
image

**Lich**
image

### Local Site
**Gnoll**
image

**Aboleth**
image

**Lich**
image

### CODE REVIEW

**Comment by eepMoody** [comment]
@drewdoesdev I'm trying to get our tests to re-run on this one.
Would you mind pushing a blank commit or something to try and get those to kick off? I can't figure out what happened here.

**Comment by drewdoesdev** [comment]
Thanks you @calumbell and @eepMoody !  I've re-pushed my branch with some comments added above the stat block sections on the stat blocks to trigger a rebuild.  Let me know if anything ells is needed!

**Comment by calumbell** [comment]
This is a sidebar, and very much outside the scope of the issue that this PR resolves, but I think we should take a second look at how we handle the compact statblocks.

The way thing stand, we will have to maintain two seperate monster pages for the regular and compact versions of the statblocks, and the only major difference between the two should be styling. This could be a problem long-term. My instinct is that there should only be one page with a toggle for switching between regular/compact displays of the statblocks, perhaps using a query param so that the compact block can be linked to directly.

The current URL structure for the compact block is also unhelpful for navigating the site ([/monsters/goblin](https://open5e.com/monsters/goblin) & [/monsters/compact/goblin](https://open5e.com/monsters/compact/goblin)), and breaks the Breadcrumbing by implying the existance of a `/monsters/compact` route.

I'll probably break this out into its own issue.

Thanks again to @drewdoesdev for making this fix!

**Comment by drewdoesdev** [comment]
@calumbell No problem, though it seems like the build steps aren't running for some reason...trying to determine what's different between my MR and, say, this one which does have the steps https://github.com/open5e/open5e/pull/455

**Comment by calumbell** [comment]
Fairly certain this is an issue on our end, looks like something has gotten stuck in our checks. I'll look into it when I am not very sleepy. Thanks again!

**Comment by calumbell** [comment]
Alright, so still digging around for a solution to whatever is going on with our PR validation. But I have seen several reports that closing & re-opening the PR sometimes helps. So I am going to give that a go now

**Pull request merged**
