### PR TITLE
Feature: Breadcrumbs #273

### PR DESCRIPTION
**Pull request by calumbell**
This PR closes issue #273. Breadcrumbs are now created dynamically using the route for each page.

Screenshot 2023-07-03 at 22 21 32

I have also renamed some pages to make them play nice with the breadcrumbing, but it also serves to improve the overall  website structure by removing unnecessary route nesting

- The monster list has been moved from `/monsters/monster-list` to `/monsters`
- The magic item list has been moved from `/magicitems/magicitem-list` to `/magicitems`
- The spell list has been moved from `/spells/spells-table` to `/spells`

I have been careful to make sure that links to specific monsters, magic items, and spells are exactly the same as they were before these changes (I would have loved to add a dash to `/magicitems` so that the breadcrumb renders this as two seperate words, but this would break existing links to specific spells)

Screenshot 2023-07-03 at 22 35 08

The existance of the `/spells/by-class/[charclass]` route implied the existance of a `/spells/by-class` route, so I went ahead and added that in (it is just a list of links to the different class specific spell lists). Nothing fancy but it gets the job done.

Screenshot 2023-07-03 at 22 35 55

### CODE REVIEW

**Comment by eepMoody** [comment]
Do you think it'd be feasible to set up a [redirect](https://router.vuejs.org/guide/essentials/redirect-and-alias.html) for the removed pages?

They've been up for quite a while, and I'm betting there's at least some links to them out there. A redirect would keep those links live while still letting the cool new breadcrumbs render properly.

**Comment by calumbell** [comment]
Sure! I'll look into it

**Comment by calumbell** [comment]
Okay, redirects are up an running, all existing links to the website should continue to work

- `/monsters/monster-list` redirects to `/monsters`
- `/spells/spells-table` redirects to `/spells`
- `/magicitems/magicitem-list` redirects to `/magic-items`
- `/magicitems/{id}` redirects to `/magic-items/{id}`

Let me know if you'd like anything else changed!

**Review by eepMoody — APPROVED** [review]

**Comment by eepMoody** [comment]
Nope, all looks good to me! Merged it in. Also all the tests passed, but they're randomly showing up as in-progress for some reason. I abused some admin powers to make sure stuff went through smoothly. :)

**Pull request merged**
